before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - mkdir -p ~/.aws
  - echo "[default]" > ~/.aws/config
  - echo "region=$AWS_DEFAULT_REGION" >> ~/.aws/config
  - echo "[default]" > ~/.aws/credentials
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
   
script:
  - $TRAVIS_BUILD_DIR/package.sh
  - $TRAVIS_BUILD_DIR/upload.sh
